name: Build and Push Docker Images

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - variant: gpu
            build-args: ""
          - variant: cpu
            build-args: |
              BASE_IMAGE=ubuntu:22.04
              JAX_PACKAGE=jax
              JAX_PLATFORMS_DEFAULT=cpu
              XLA_FLAGS_DEFAULT=--xla_dump_to=/output/hlo_dumps_xla --xla_dump_hlo_as_text --xla_dump_hlo_as_html=true --xla_cpu_enable_xprof_traceme --xla_gpu_deterministic_ops

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mbirjax-profiler:${{ matrix.variant }}
          build-args: ${{ matrix.build-args }}
